import React from 'react';

export const ProtectData = () => {
  // Styles moved to a constant to maintain the 1.1em font size request
  const containerStyle = {
    fontFamily: 'Arial, sans-serif',
    lineHeight: '1.6',
    margin: '20px auto',
    backgroundColor: '#f4f4f9',
    color: '#333',
    maxWidth: '90%',
    fontSize: '1.1em', // Larger font applied as requested [cite: 2025-05-09]
    padding: '20px',
    borderRadius: '8px'
  };

  const headerStyle = {
    color: '#cc0052',
    borderBottom: '2px solid #cc0052',
    paddingBottom: '10px',
    marginBottom: '20px'
  };

  const detailsStyle = {
    backgroundColor: '#ffffff',
    border: '1px solid #ddd',
    borderRadius: '8px',
    marginBottom: '10px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
    overflow: 'hidden'
  };

  const summaryStyle = {
    fontWeight: 'bold',
    padding: '15px 20px',
    cursor: 'pointer',
    color: '#007bff',
    listStyle: 'none',
    borderBottom: '1px solid #eee'
  };

  const contentStyle = {
    padding: '15px 20px'
  };

  return (
    <div style={containerStyle}>
      <h1 style={headerStyle}>CRUK Data Protection and Access Information</h1>

      <details style={detailsStyle} open>
        <summary style={summaryStyle}>How We Protect Your Data</summary>
        <div style={contentStyle}>
          <p>
            Our goal is to help researchers find and reuse data generated by CRUK research projects making every donation work harder to cure cancer.
            The Datahub provides an overview of the datasets stored by research projects and contains no sensitive patient data.
            Where the datasets include sensitive patient data access is heavily controlled to make sure that the research is in the public interest,
            that the minimum data is used by trusted people in a safe setting, and that results do not disclose any personal data.
          </p>
        </div>
      </details>

      <details style={detailsStyle}>
        <summary style={summaryStyle}>Accessing Cancer Data</summary>
        <div style={contentStyle}>
          <p>
            Once researchers have found a dataset of interest, they can use the hub to request access.
            Many of these datasets include sensitive patient data. For these, access is guarded by a robust legal and ethical framework
            and access is controlled by a <strong>Data Access Committee</strong>. There are strict controls on how researchers can access health data information.
            The purpose must be approved before anyone can use the data, and they are only given access to the minimum amount of data necessary.
          </p>
          <p>The types of organisations that may use health data include:</p>
          <ul>
            <li><strong>Researchers:</strong> use data for research and innovation such as to understand the causes of disease, to develop new ways of diagnosing illness or to identify ways to develop new treatments</li>
            <li><strong>NHS providers, charities and commissioners:</strong> use data to improve care. They monitor trends and patterns in health activity, evaluate services and assess how care is provided, and to support local service planning.</li>
            <li><strong>Companies partnered with the NHS:</strong> may also take part in some of these activities.</li>
          </ul>
        </div>
      </details>

      <details style={detailsStyle}>
        <summary style={summaryStyle}>Legal and Ethical Framework</summary>
        <div style={contentStyle}>
          <p>Using identifiable health data in research means following a robust framework:</p>
          <ul>
            <li>Under <strong>common law confidentiality</strong>, researchers must respect the trust placed in them by data subjects.</li>
            <li><strong>UK GDPR and the Data Protection Act 2018</strong> require personal data to be handled lawfully, fairly, and transparently.</li>
          </ul>
          <p>This does not necessarily mean that researchers need explicit consent to use patient data. For example, they may be granted approval through a research ethics committee.</p>
        </div>
      </details>

      <details style={detailsStyle}>
        <summary style={summaryStyle}>Lawful Basis for Cancer Research</summary>
        <div style={contentStyle}>
          <p>Most cancer research doesn’t rely on individual consent as the legal basis for processing data. Instead, organisations often rely on:</p>
          <ul>
            <li><strong>Public task</strong> – for institutions like universities or public research bodies</li>
            <li><strong>Legitimate interest</strong> – more commonly used by charities or commercial research teams</li>
          </ul>
          <p>
            For <strong>special category data</strong> such as cancer diagnoses, treatment records, and genomic information,
            an additional lawful condition must also be met under <strong>Article 9 of the UK GDPR</strong>.
            Specifically, Article 9(2)(j) permits the processing of special category data when it is necessary for scientific research purposes,
            provided that appropriate safeguards are in place in accordance with Article 89(1). These safeguards include data minimisation,
            pseudonymisation, and strong governance practices to protect individuals’ rights and freedoms.
          </p>
        </div>
      </details>

      <details style={detailsStyle}>
        <summary style={summaryStyle}>Secure Environments</summary>
        <div style={contentStyle}>
          <p>Personal data requires secure environments and specialist knowledge to use responsibly.</p>
          <p>
            Many of the datasets funded through CRUK are stored in Trusted Research Environments (TREs) and Secure Data Environments (SDEs),
            which offer a safe space to explore these rich datasets without compromising privacy by accessing and analysing data without
            downloading it or compromising its security.
          </p>
        </div>
      </details>
    </div>
  );
};

